# Generated by Django 5.2.4 on 2025-08-01 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('applicant', 'Applicant')], default='applicant', max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('high_school', models.CharField(blank=True, max_length=100)),
                ('year_graduated', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='applicant_photos/')),
                ('application_status', models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('verified', 'Verified Documents'), ('exam_taken', 'Exam Taken'), ('passed', 'Passed'), ('failed', 'Failed'), ('admitted', 'Admitted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('exam_status', models.CharField(blank=True, choices=[('not_taken', 'Not Taken'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_taken', max_length=20)),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('course_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
