# Generated by Django 5.2.4 on 2025-08-01 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
