# Generated by Django 5.2.4 on 2025-08-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_choice_exam_applicantexam_question_choice_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
    ]
