# Generated by Django 5.2.4 on 2025-08-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_exam_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantanswer',
            name='multiple_submission_flag',
            field=models.BooleanField(default=False, verbose_name='Multiple Submissions'),
        ),
        migrations.AddField(
            model_name='applicantanswer',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Tab Switches'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Marks whether the exam has expired', verbose_name='Is Expired'),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of allowed attempts', verbose_name='Max Attempts'),
        ),
        migrations.AlterField(
            model_name='applicantanswer',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Time Spent (sec)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='access_code',
            field=models.CharField(blank=True, help_text='Code required to access the exam', max_length=10, verbose_name='Access Code'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(verbose_name='Exam Date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the exam', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration of the exam in minutes', verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(help_text='Title of the exam', max_length=100, verbose_name='Exam Title'),
        ),
    ]
