# Generated by Django 5.2.4 on 2025-09-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_applicantanswer_multiple_submission_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.AddField(
            model_name='exam',
            name='max_applicants',
            field=models.PositiveIntegerField(default=30, verbose_name='Max Applicants'),
        ),
    ]
