# Generated by Django 5.2.4 on 2025-09-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_question_correct_choice_exam_max_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='min_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
