# Generated by Django 5.2.4 on 2025-09-25 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_course_min_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantexam',
            name='recommended_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_exams', to='api.course'),
        ),
    ]
