# Generated by Django 5.2.4 on 2025-11-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_applicantexam_recommended_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicantexam',
            unique_together=set(),
        ),
    ]
